# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/parallels/Documents/ECEC302/RAM_FIFO/RAM_FIFO.cache/wt [current_project]
set_property parent.project_path /home/parallels/Documents/ECEC302/RAM_FIFO/RAM_FIFO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip /home/parallels/Documents/ECEC302/RAM_FIFO/RAM_FIFO.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/parallels/Documents/ECEC302/RAM_FIFO/RAM_FIFO.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc]
set_property is_locked true [get_files /home/parallels/Documents/ECEC302/RAM_FIFO/RAM_FIFO.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

read_vhdl -library xil_defaultlib /home/parallels/Documents/ECEC302/RAM_FIFO/RAM_FIFO.srcs/sources_1/new/fifo_4x16.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top fifo_4x16 -part xc7a35tcpg236-1
write_checkpoint -noxdef fifo_4x16.dcp
catch { report_utilization -file fifo_4x16_utilization_synth.rpt -pb fifo_4x16_utilization_synth.pb }
