# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/parallels/Documents/ECEC302/radix_adder/radix_adder.cache/wt [current_project]
set_property parent.project_path /home/parallels/Documents/ECEC302/radix_adder/radix_adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /home/parallels/Documents/ECEC302/radix_adder/radix_adder.srcs/sources_1/new/rad_add.vhd
read_xdc /home/parallels/Documents/ECEC302/radix_adder/radix_adder.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files /home/parallels/Documents/ECEC302/radix_adder/radix_adder.srcs/constrs_1/new/const.xdc]

catch { write_hwdef -file rad_add.hwdef }
synth_design -top rad_add -part xc7a35tcpg236-1
write_checkpoint -noxdef rad_add.dcp
catch { report_utilization -file rad_add_utilization_synth.rpt -pb rad_add_utilization_synth.pb }
